---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
# library(GEOquery)
library(beadarray)
library(lumi)
library(arrayQualityMetrics)
library(ggplot2)
library(limma)
library(reshape2)
library(illuminaMousev2.db)
library(pheatmap)

library(lumiMouseIDMapping)
library(lumiMouseAll.db)
library(annotate)
library(AnnotationDbi)
# library(WGCNA)

library(reshape2)
library(plyr)
library(dplyr)
# library(broom)
library(magrittr)
# library(purrr)
library(stringr)
library(readr)
require("knitr")
opts_knit$set(root.dir = "/mnt/data8/zhaoyuancun/microarray")
```


```{r}

# Varification of Parasites not Affecting Experiment

fileList <- c("HJ_CG_JeanLangh_JW_220813_Sample_Probe_Profile.txt")
x.lumi <- lumiR.batch(fileList = fileList, lib.mapping = 'lumiMouseIDMapping', convertNuID = T)
pData <- read.csv("SampleInfo.csv", row.names = 1)

sampleNames(x.lumi) <- rownames(pData[match(x.lumi$sampleID, rownames(pData)),])
pData(x.lumi) <- pData[match(x.lumi$sampleID, rownames(pData)),]

# Remove bad samples
badsamp <- c("8697771087_E","8697771096_F")
toremove <- rownames(pData(x.lumi)) %in% badsamp
x.lumi.badremove = x.lumi[,-which(toremove)]

detDat <- detection(x.lumi.badremove)
ggplot(data=melt(detDat), aes(x = Var2, y = value)) + 
  geom_violin() +
  geom_boxplot(width=0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Detection Pval") +
  xlab("Sample") +
  ylab("Detection Pval")

# pdf(file = "fig/True_detection.pdf")
True_Detection <- as.data.frame(colSums(detection(x.lumi.badremove) <= 0.01 ))
ggplot(data = True_Detection, aes(x = rownames(True_Detection),
                                  y = True_Detection[,1], group = 1,
                                  label = True_Detection[,1])) +
  geom_point() +
  geom_line(linetype = 2) +
  geom_text(vjust = -1, nudge_y = 0.5) +
  ggtitle("True Detection") +
  xlab("Samples") +
  ylab("Detected Probes") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  scale_x_discrete(labels = c("naïve", "infected", "infected", "naïve", "infected", "infected", "naïve", "parasite", "infected", "parasite"))
# dev.off()

###Generate QC plots

pdf(file = "fig/density_plot.pdf")
plot(x.lumi.badremove, what = "density")
dev.off()

pdf(file = "fig/Cumulative_plot_of_density.pdf")
plotCDF(x.lumi.badremove, reverse = T)
dev.off()

# Density plot using ggplot2

expr <- exprs(x.lumi.sub.T)
if (max(expr, na.rm = TRUE) > 50) {
  if (min(expr, na.rm = TRUE) < 0) {
    rMin <- rowMin(expr)
    expr <- expr[rMin > 0, , drop = FALSE]
    }
  expr <- log2(expr)
}
expr <- expr %>% t %>% data.frame(Sample.Name = sampleNames(x.lumi.sub.T),
                                                                      infection = x.lumi.sub.T$infection,
                                                                      parasite = x.lumi.sub.T$parasite)
expr.melt <- melt(expr, id = c("Sample.Name", "infection", "parasite"))
colnames(expr.melt)[4:5] <- c("Symbol", "Intensity")

# pdf(file = "fig/Histogram_of_Expression_density.pdf")
ggplot(expr.melt, aes(Intensity, group = Sample.Name, col = parasite)) +
  stat_density(position="identity",geom="line",linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Histogram of Expression") + ylab("Density") + xlab("Expression")
# dev.off()


pdf(file = "fig/density_with_parasites.pdf")
plot(x.lumi.badremove, what = "density")
dev.off()

# plot(x.lumi.badremove, what = 'pair')
# pairs(x.lumi.badremove, smoothScatter = T)
# MAplot(x.lumi.badremove, smoothScatter = T)
plot(x.lumi.badremove, what = 'boxplot')
plot(x.lumi.badremove, what = 'sampleRelation')
plotSampleRelation(x.lumi.badremove, method = 'mds')
plotSampleRelation(x.lumi.badremove, method = 'cluster')

##Do default VST variance stabilizing transform

# x.lumi.sub.B <- lumiB(x.lumi.sub, method = 'forcePositive')

x.lumi.noparasite <- x.lumi.badremove[,x.lumi.badremove$parasite == 'No']

x.lumi.sub.T <- lumiT(x.lumi.noparasite, method = 'log2')

##Plot VST transformation

trans <- plotVST(x.lumi.sub.T)
matplot(log2(trans$untransformed), trans$transformed)

##Do quantile between microarray normaliazation
x.lumi.sub.TN <- lumiN(x.lumi.sub.T)

##Do quality control estimation after normalization
x.lumi.sub.TNQ <- lumiQ(x.lumi.sub.TN)


###Generate QC plots after normalisation
plotCDF(x.lumi.sub.TNQ, reverse = T)
plotSampleRelation(x.lumi.sub.TNQ, method = 'mds')
plotSampleRelation(x.lumi.sub.TNQ, method = 'cluster')

# The PCA plot of the vst-transformed raw expression data
exp_raw <- exprs(x.lumi.sub.TNQ)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                    infection = pData(x.lumi.sub.TNQ)$"infection")

pdf(file = "fig/PCA_of_infected_vs._naïve.pdf")
ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(shape = infection), size = 3, col = "royalblue") +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      ggtitle("PCA plot of infected vs. naïve expression data") +
      xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
      ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)+
      coord_fixed(ratio = sd_ratio) +
      scale_shape_manual(values = c(17,15,16))
dev.off()

probeList <- rownames(x.lumi.badremove)
geneSymbol <- sapply(probeList %>% lookUp('lumiMouseAll.db', what = "SYMBOL"), function(x) x[1])




```




```{r}

# Raw data reading

fileList <- c("HJ_CG_JeanLangh_JW_220813_Sample_Probe_Profile.txt",
              "HJ_JLanghorne_NoURNA_bkgsubt_NoNorm_110913_Sample_Probe_Profile.txt",
              "HJ_JWL_181213_NouRNA_Bkg_subt_noNorm_SampleProbeProfile.txt",
              "HJ_JingWen_7chip__011113_NouRNA_NoParasite_Bkg_Subtracted_No_Norm_Sample_Probe_Profile.txt")

x.lumi <- lumiR.batch(fileList = fileList, lib.mapping = 'lumiMouseIDMapping', convertNuID = F)
pData <- read.csv("SampleInfo_GEO.csv", row.names = 1)

x.lumi.GEO <- x.lumi[,match(pData$"slot", x.lumi$sampleID)]

sampleNames(x.lumi.GEO) <- rownames(pData[match(x.lumi.GEO$sampleID,
                                                pData[,"slot"]),])
pData(x.lumi.GEO) <- pData

x.lumi.GEO.AS <- x.lumi.GEO[,x.lumi.GEO$type == "AS"]

x.lumi.GEO.AS.blood <- x.lumi.GEO.AS[,x.lumi.GEO.AS$tissue == "blood"]

x.lumi.GEO.AS.spleen <- x.lumi.GEO.AS[,x.lumi.GEO.AS$tissue == "spleen"]

x.lumi.GEO.CB <- x.lumi.GEO[,x.lumi.GEO$type == "CB"]

x.lumi.GEO.CB.blood <- x.lumi.GEO.CB[,x.lumi.GEO.CB$tissue == "blood"]

x.lumi.GEO.CB.spleen <- x.lumi.GEO.CB[,x.lumi.GEO.CB$tissue == "spleen"]

```

```{r}

# Data from AS Blood

detDat <- detection(x.lumi.GEO.AS.blood)
ggplot(data=melt(detDat), aes(x = Var2, y = value)) + 
  geom_violin() +
  geom_boxplot(width=0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Detection Pval") +
  xlab("Sample") +
  ylab("Detection Pval")

True_Detection <- as.data.frame(colSums(detection(x.lumi.GEO.AS.blood) <= 0.01 ))

# pdf(file = "fig/True_Detection_of_blood.pdf")
ggplot(data = True_Detection, aes(x = rownames(True_Detection),
                                  y = True_Detection[,1], group = 1,
                                  label = True_Detection[,1])) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  geom_point() +
  geom_line(linetype = 2) +
  geom_text(vjust = -1, nudge_y = 0.5) +
  ggtitle("True Detection") +
  xlab("Samples") +
  ylab("Detected Probes") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  scale_x_discrete(labels = paste(x.lumi.GEO.AS.blood$infection,
                                  x.lumi.GEO.AS.blood$day) )
# dev.off()


```

```{r}

##Do default VST variance stabilizing transform

# x.lumi.sub.B <- lumiB(x.lumi.sub, method = 'forcePositive')
x.lumi.sub.T <- lumiT(x.lumi.GEO.AS.blood, method = 'log2')

##Plot VST transformation

# trans <- plotVST(x.lumi.sub.T)
# matplot(log2(trans$untransformed), trans$transformed)

##Do quantile between microarray normaliazation
x.lumi.sub.TN <- lumiN(x.lumi.sub.T)

##Do quality control estimation after normalization
x.lumi.sub.TNQ <- lumiQ(x.lumi.sub.TN)


###Generate QC plots after normalisation
# pdf(file = "fig/Density_plot_of_intensity.pdf")
# plot(x.lumi.sub.TNQ, what = 'density', main = "Density plot of blood sample intensity")
# dev.off()

# Density plot using ggplot2

expr <- exprs(x.lumi.sub.TNQ)
if (max(expr, na.rm = TRUE) > 50) {
  if (min(expr, na.rm = TRUE) < 0) {
    rMin <- rowMin(expr)
    expr <- expr[rMin > 0, , drop = FALSE]
    }
  expr <- log2(expr)
}
expr.x.lumi.sub.TNQ <- expr %>% t %>% data.frame(Sample.Name = sampleNames(x.lumi.sub.TNQ),
                      infection = x.lumi.sub.TNQ$infection)
expr.melt <- melt(expr.x.lumi.sub.TNQ, id = c("Sample.Name", "infection"))
colnames(expr.melt)[3:4] <- c("Symbol", "Intensity")

# pdf(file = "fig/Histogram_of_blood_Expression_density.pdf")
ggplot(expr.melt, aes(Intensity, group = Sample.Name, col = infection, linetype = infection)) +
  stat_density(position="identity",geom = "line") +
  scale_linetype_manual(values=c("1F", "solid")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Histogram of Expression") + ylab("Density") + xlab("Expression")
# dev.off()

plotCDF(x.lumi.sub.TNQ, reverse = T)
# plot(x.lumi.sub.TNQ, what = 'boxplot')

randIDs <- sample(featureNames(x.lumi.sub.TNQ), 3000)

# pdf(file = "fig/Boxplot_of_blood_sample_microarray_intensity.pdf")
ggplot( melt(exprs(x.lumi.sub.TNQ[randIDs,])) , aes(x = Var2, y = value) ) +
  stat_boxplot(geom = "errorbar", width = 0.3) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
  geom_boxplot(outlier.shape = 1, outlier.size = 0.1, alpha = 1/3) +
  # geom_jitter(shape=".", position=position_jitter(0.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1) ) +
  scale_x_discrete(labels = paste(x.lumi.GEO.AS.blood$infection,
                                  x.lumi.GEO.AS.blood$day) ) +
  ggtitle("Boxplot of blood sample microarray intensity") +
  xlab("Sample") +
  ylab("VST transformed intensity (Rnd sampled 3000)")
# dev.off()

# plot(x.lumi.sub.TNQ, what = 'pair')
# pairs(x.lumi.sub.TNQ, smoothScatter = T)
# MAplot(x.lumi.sub.TNQ, smoothScatter = T)
plotSampleRelation(x.lumi.sub.TNQ, method = 'mds')

# pdf(file = "fig/Sample_cluster_of_blood.pdf")
plotSampleRelation(x.lumi.sub.TNQ, method = 'cluster',
                   labels = paste(x.lumi.sub.TNQ$infection, x.lumi.sub.TNQ$day))
# dev.off()

# The PCA plot of the vst-transformed raw expression data
exp_raw <- exprs(x.lumi.sub.TNQ)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                    infection = pData(x.lumi.GEO.AS.blood)$"infection",
                    day = pData(x.lumi.GEO.AS.blood)$"day")

# pdf(file = "fig/PCA_plot_of_VST_INFvNAIVE.pdf")
ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(shape = infection, colour = day), size = 3) +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      ggtitle("PCA plot of the vst-transformed infected vs. naïve") +
      xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
      ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)+
      coord_fixed(ratio = sd_ratio) +
      scale_shape_manual(values = c(17,15)) + 
      # scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00"))
      scale_color_manual(values = c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#ffff99", "#b15928"))
# dev.off()


# Heatmap clusterring

annotation_for_heatmap <- data.frame(infection = pData(x.lumi.sub.TNQ)$"infection", day = pData(x.lumi.sub.TNQ)$"day")

row.names(annotation_for_heatmap) <- row.names(pData(x.lumi.sub.TNQ))

dists <- as.matrix(dist(t(exp_raw), method = "euclidean"))

rownames(dists) <- row.names(pData(x.lumi.sub.TNQ))
hmcol <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd"))(255))
colnames(dists) <- NULL
diag(dists) <- NA

ann_colors <- list(infection = c(naïve = "cadetblue2", infected = "blue4"),
                   day = c(D0 = "#1f78b4", D10 = "#33a02c", D12 = "#e31a1c", D2 = "#ff7f00", D4 = "#6a3d9a", D6 = "#ffff99", D8 = "#b15928"))
# pdf(file = "fig/Heatmap_for_vst_AS_blood.pdf")
pheatmap(dists, col = (hmcol),
         cellwidth = 10,
         cellheight = 10,
         labels_row = paste(x.lumi.GEO.AS.blood$infection, x.lumi.GEO.AS.blood$day),
         # annotation_row = annotation_for_heatmap,
         # annotation_colors = ann_colors,
         legend = TRUE, 
         treeheight_col = 0,
         # cluster_rows = T, 
         # cluster_cols = F, 
         # legend_breaks = c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE)), 
         # color = colorRampPalette(colors = c("blue","white","red")),
         # legend_labels = (c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE))),
         main = "Heatmap for vst-transformed AS blood")
# dev.off()
```

```{r}

# Data from CB Blood

detDat <- detection(x.lumi.GEO.CB.blood)
ggplot(data=melt(detDat), aes(x = Var2, y = value)) + 
  geom_violin() +
  geom_boxplot(width=0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Detection Pval") +
  xlab("Sample") +
  ylab("Detection Pval")

True_Detection <- as.data.frame(colSums(detection(x.lumi.GEO.CB.blood) <= 0.01 ))

# pdf(file = "fig/True_Detection_of_CB_blood.pdf")
ggplot(data = True_Detection, aes(x = rownames(True_Detection),
                                  y = True_Detection[,1], group = 1,
                                  label = True_Detection[,1])) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  geom_point() +
  geom_line(linetype = 2) +
  geom_text(vjust = -1, nudge_y = 0.5) +
  ggtitle("True Detection") +
  xlab("Samples") +
  ylab("Detected Probes") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  scale_x_discrete(labels = paste(x.lumi.GEO.CB.blood$infection,
                                  x.lumi.GEO.CB.blood$day) )
# dev.off()


```

```{r}

##Do default VST variance stabilizing transform

# x.lumi.sub.B <- lumiB(x.lumi.sub, method = 'forcePositive')
x.lumi.sub.T <- lumiT(x.lumi.GEO.CB.blood, method = 'log2')

##Plot VST transformation

# trans <- plotVST(x.lumi.sub.T)
# matplot(log2(trans$untransformed), trans$transformed)

##Do quantile between microarray normaliazation
x.lumi.sub.TN <- lumiN(x.lumi.sub.T)

##Do quality control estimation after normalization
x.lumi.sub.TNQ <- lumiQ(x.lumi.sub.TN)


###Generate QC plots after normalisation
# pdf(file = "fig/Density_plot_of_intensity.pdf")
# plot(x.lumi.sub.TNQ, what = 'density', main = "Density plot of blood sample intensity")
# dev.off()

# Density plot using ggplot2

expr <- exprs(x.lumi.sub.TNQ)
if (max(expr, na.rm = TRUE) > 50) {
  if (min(expr, na.rm = TRUE) < 0) {
    rMin <- rowMin(expr)
    expr <- expr[rMin > 0, , drop = FALSE]
    }
  expr <- log2(expr)
}
expr.x.lumi.sub.TNQ <- expr %>% t %>% data.frame(Sample.Name = sampleNames(x.lumi.sub.TNQ),
                      infection = x.lumi.sub.TNQ$infection)
expr.melt <- melt(expr.x.lumi.sub.TNQ, id = c("Sample.Name", "infection"))
colnames(expr.melt)[3:4] <- c("Symbol", "Intensity")

# pdf(file = "fig/Histogram_of_blood_Expression_density.pdf")
ggplot(expr.melt, aes(Intensity, group = Sample.Name, col = infection, linetype = infection)) +
  stat_density(position="identity",geom = "line") +
  scale_linetype_manual(values=c("1F", "solid")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Histogram of Expression") + ylab("Density") + xlab("Expression")
# dev.off()

plotCDF(x.lumi.sub.TNQ, reverse = T)
# plot(x.lumi.sub.TNQ, what = 'boxplot')

randIDs <- sample(featureNames(x.lumi.sub.TNQ), 3000)

# pdf(file = "fig/Boxplot_of_CB_blood_sample_microarray_intensity.pdf")
ggplot( melt(exprs(x.lumi.sub.TNQ[randIDs,])) , aes(x = Var2, y = value) ) +
  stat_boxplot(geom = "errorbar", width = 0.3) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
  geom_boxplot(outlier.shape = 1, outlier.size = 0.1, alpha = 1/3) +
  # geom_jitter(shape=".", position=position_jitter(0.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1) ) +
  scale_x_discrete(labels = paste(x.lumi.GEO.CB.blood$infection,
                                  x.lumi.GEO.CB.blood$day) ) +
  ggtitle("Boxplot of blood sample microarray intensity") +
  xlab("Sample") +
  ylab("VST transformed intensity (Rnd sampled 3000)")
# dev.off()

# plot(x.lumi.sub.TNQ, what = 'pair')
# pairs(x.lumi.sub.TNQ, smoothScatter = T)
# MAplot(x.lumi.sub.TNQ, smoothScatter = T)
plotSampleRelation(x.lumi.sub.TNQ, method = 'mds')

# pdf(file = "fig/Sample_cluster_of_CB_blood.pdf")
plotSampleRelation(x.lumi.sub.TNQ, method = 'cluster',
                   labels = paste(x.lumi.sub.TNQ$infection, x.lumi.sub.TNQ$day))
# dev.off()

# The PCA plot of the vst-transformed raw expression data
exp_raw <- exprs(x.lumi.sub.TNQ)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                    infection = pData(x.lumi.GEO.CB.blood)$"infection",
                    day = pData(x.lumi.GEO.CB.blood)$"day")

# pdf(file = "fig/PCA_plot_of_CB_blood_log2.pdf")
ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(shape = infection, colour = day), size = 3) +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      ggtitle("PCA plot of the vst-transformed infected vs. naïve") +
      xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
      ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)+
      coord_fixed(ratio = sd_ratio) +
      scale_shape_manual(values = c(17,15)) + 
      # scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00"))
      scale_color_manual(values = c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#ffff99", "#b15928", "#999999"))
# dev.off()


# Heatmap clusterring

annotation_for_heatmap <- data.frame(infection = pData(x.lumi.sub.TNQ)$"infection", day = pData(x.lumi.sub.TNQ)$"day")

row.names(annotation_for_heatmap) <- row.names(pData(x.lumi.sub.TNQ))

dists <- as.matrix(dist(t(exp_raw), method = "euclidean"))

rownames(dists) <- row.names(pData(x.lumi.sub.TNQ))
hmcol <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd"))(255))
colnames(dists) <- NULL
diag(dists) <- NA

ann_colors <- list(infection = c(naïve = "cadetblue2", infected = "blue4"),
                   day = c(D0 = "#1f78b4", D10 = "#33a02c", D12 = "#e31a1c", D2 = "#ff7f00", D4 = "#6a3d9a", D6 = "#ffff99", D8 = "#b15928", D9 = "#999999"))
# pdf(file = "fig/Heatmap_for_vst_CB_blood.pdf")
pheatmap(dists, col = (hmcol),
         cellwidth = 10,
         cellheight = 10,
         labels_row = paste(x.lumi.GEO.CB.blood$infection, x.lumi.GEO.CB.blood$day),
         # annotation_row = annotation_for_heatmap,
         # annotation_colors = ann_colors,
         legend = TRUE, 
         treeheight_col = 0,
         # legend_breaks = c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE)), 
         # color = colorRampPalette(colors = c("blue","white","red")),
         # legend_labels = (c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE))),
         main = "Heatmap for vst-transformed CB blood")
# dev.off()
```





```{r}

# Volcano plot

design <- model.matrix(~ 0 + factor(pData(x.lumi.sub.TNQ)$infection))
colnames(design) <- c('infected', 'naïve')
design
fit <- lmFit(x.lumi.sub.TNQ, design)
contrast.matrix <- makeContrasts(naïve - infected, levels = design)

fit2 <- contrasts.fit(fit,contrast.matrix)
fit2 <- eBayes(fit2)

## Add gene symbols to gene properties
probeList <- rownames(x.lumi.sub.TNQ)
geneSymbol <- sapply(probeList %>% lookUp('lumiMouseAll.db', what = "SYMBOL"), function(x) x[1])
geneName <- sapply(probeList %>% lookUp('lumiMouseAll.db', what = "GENENAME"), function(x) x[1])

fit2$genes <- data.frame(ProbeID = fit2$genes$ProbeID, TargetID = fit2$genes$TargetID,
                         geneSymbol = geneSymbol, geneName = geneName)

# top.table.contrasts <- topTable(fit2, number = Inf)
# top.table <- topTable(eBayes(fit))
# 
# decide.table <- decideTests(fit2, adjust.method = "fdr", p = 0.05)
# decide.df <- data.frame(Gene = rownames(decide.table), Direction = as.vector(decide.table))

p.fdr = p.adjust(fit2$p.value[,1],method = "fdr")
plot(fit2$coefficients[,1],-log10(p.fdr),xlab = "Contrast estimate",
     ylab = "-log10(pvalue)",main = "",cex = 0.6, pch = 19)
points(fit2$coefficients[,1][p.fdr < 0.05],-log10(p.fdr)[p.fdr < 0.05],
       cex = 0.6, pch = 19, col = "red")
abline(h = -log10(0.05),col = "blue",lty =2,lwd = 1.5)




volcano_names <- ifelse(abs(fit2$coefficients)>=1, 
                        fit2$genes$geneSymbol, NA)
volcanoplot(fit2, coef = 1L, style = "p-value", highlight = 1000,
            names = volcano_names,
            xlab = "Log2 Fold Change", ylab = NULL, pch=16, cex=0.35)

```

```{r}

#Collapse Rows
k <- AnnotationDbi::keys(illuminaMousev2.db,keytype="PROBEID")
expr.symbols <- AnnotationDbi::mapIds(illuminaMousev2.db, keys=k, column=c("ENSEMBL"), keytype="PROBEID")

expr.symbols <- sapply(featureNames(x.lumi.sub.TNQ) %>% lookUp('illuminaMousev2.db', what = "ENSEMBL"), function(x) x[1]) %>% factor
# expr.symbols <- featureNames(x.lumi.sub.TNQ) %>% mapIds(illuminaMousev2.db, keys=k, column=c("ENSEMBL"), keytype="PROBEID") %>% factor
expr.collapse <- collapseRows(exprs(x.lumi.sub.TNQ), rowGroup = expr.symbols, rowID = rownames(exprs(x.lumi.sub.TNQ)))
lumi.collapse <- ExpressionSet(assayData = expr.collapse$datETcollapsed, phenoData = phenoData(x.lumi.sub.TNQ))

## Add gene symbols to gene properties
# if (require(lumiMouseAll.db) & require(annotate)) {
#  geneSymbol <- getSYMBOL(probeList, 'lumiMouseAll.db')
#  geneName <- sapply(lookUp(probeList, 'lumiMouseAll.db', 'GENENAME'), function(x) x[1] )
#  fit$genes <- data.frame(ID= probeList, geneSymbol=geneSymbol, geneName=geneName, stringsAsFactors = FASLE)
# }
RefSeq = nuID2RefSeqID(row.names(x.lumi.sub.TNQ),
                       lib.mapping='lumiMouseIDMapping',returnAllInfo = TRUE )
Annot = RefSeq[row.names(RefSeq) %in% row.names(exprs(x.lumi.sub.TNQ)),]
```









```{r}

# Data from AS Spleen

detDat <- detection(x.lumi.GEO.AS.spleen)
ggplot(data=melt(detDat), aes(x = Var2, y = value)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Detection Pval") +
  xlab("Sample") +
  ylab("Detection Pval")

True_Detection <- as.data.frame(colSums(detection(x.lumi.GEO.AS.spleen) <= 0.01 ))
# pdf(file = "fig/True_Detection_of_spleen.pdf")
ggplot(data = True_Detection, aes(x = rownames(True_Detection),
                                  y = True_Detection[,1], group = 1,
                                  label = True_Detection[,1])) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  geom_point() +
  geom_line(linetype = 2) +
  geom_text(vjust = -1, nudge_y = 0.5) +
  ggtitle("True Detection") +
  xlab("Samples") +
  ylab("Detected Probes") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  scale_x_discrete(labels = paste(x.lumi.GEO.AS.spleen$infection,
                                  x.lumi.GEO.AS.spleen$day) )
# dev.off()

###Generate QC plots

plot(x.lumi.GEO.AS.spleen, what = 'density')
plotCDF(x.lumi.GEO.AS.spleen, reverse = T)
# plot(x.lumi.GEO.AS.spleen, what = 'pair')
# pairs(x.lumi.GEO.AS.spleen, smoothScatter = T)
MAplot(x.lumi.GEO.AS.spleen, smoothScatter = T)
plot(x.lumi.GEO.AS.spleen, what = 'boxplot')
plotSampleRelation(x.lumi.GEO.AS.spleen, method = 'mds')
plotSampleRelation(x.lumi.GEO.AS.spleen, method = 'cluster')

```

```{r}

##Do default VST variance stabilizing transform

x.lumi.sub.T <- lumiT(x.lumi.GEO.AS.spleen, method = 'log2')

##Plot VST transformation

# trans <- plotVST(x.lumi.sub.T)
# matplot(log2(trans$untransformed), trans$transformed)

##Do quantile between microarray normaliazation
x.lumi.sub.TN <- lumiN(x.lumi.sub.T)

##Do quality control estimation after normalization
x.lumi.sub.TNQ <- lumiQ(x.lumi.sub.TN)

###Generate QC plots after normalisation

plot(x.lumi.sub.TNQ, what = 'density')
# Density plot using ggplot2
expr <- exprs(x.lumi.sub.TNQ)
if (max(expr, na.rm = TRUE) > 50) {
  if (min(expr, na.rm = TRUE) < 0) {
    rMin <- rowMin(expr)
    expr <- expr[rMin > 0, , drop = FALSE]
    }
  expr <- log2(expr)
}
expr.x.lumi.sub.TNQ <- expr %>% t %>% data.frame(Sample.Name = sampleNames(x.lumi.sub.TNQ),
                      infection = x.lumi.sub.TNQ$infection)
expr.melt <- melt(expr.x.lumi.sub.TNQ, id = c("Sample.Name", "infection"))
colnames(expr.melt)[3:4] <- c("Symbol", "Intensity")

# pdf(file = "fig/Histogram_of_spleen_Expression_density.pdf")
ggplot(expr.melt, aes(Intensity, group = Sample.Name, col = infection, linetype = infection)) +
  stat_density(position="identity",geom = "line") +
  scale_linetype_manual(values=c(1, 2)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Histogram of Expression") + ylab("Density") + xlab("Expression")
# dev.off()


plotCDF(x.lumi.sub.TNQ, reverse = T)
# plot(x.lumi.sub.TNQ, what = 'boxplot')

randIDs <- sample(featureNames(x.lumi.sub.TNQ), 3000)
# pdf(file = "fig/Boxplot_of_spleen_sample_microarray_intensity.pdf")
ggplot( melt(exprs(x.lumi.sub.TNQ[randIDs,])) , aes(x = Var2, y = value) ) +
  stat_boxplot(geom = "errorbar", width = 0.3) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
  geom_boxplot(outlier.shape = 1, outlier.size = 0.1, alpha = 1/3) +
  # geom_jitter(shape=".", position=position_jitter(0.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1) ) +
  scale_x_discrete(labels = paste(x.lumi.GEO.AS.spleen$infection,
                                  x.lumi.GEO.AS.spleen$day) ) +
  ggtitle("Boxplot of spleen sample microarray intensity") +
  xlab("Sample") +
  ylab("log2 transformed intensity (Rnd sampled 3000)")
# dev.off()


# plot(x.lumi.sub.TNQ, what = 'pair')
# pairs(x.lumi.sub.TNQ, smoothScatter = T)
MAplot(x.lumi.sub.TNQ, smoothScatter = T)
plotSampleRelation(x.lumi.sub.TNQ, method = 'mds')

# pdf(file = "fig/Sample_cluster_of_spleen.pdf")
plotSampleRelation(x.lumi.sub.TNQ, method = 'cluster',
                   labels = paste(x.lumi.sub.TNQ$infection, x.lumi.sub.TNQ$day))
# dev.off()

# The PCA plot of the vst-transformed raw expression data
exp_raw <- exprs(x.lumi.sub.TNQ)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                    infection = pData(x.lumi.GEO.AS.spleen)$"infection",
                    day = pData(x.lumi.GEO.AS.spleen)$"day")

pdf(file = "fig/PCA_plot_of_log2_INFvNAIVE_spleen.pdf")
ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(shape = infection, colour = day), size = 3) +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      ggtitle("PCA plot of the log2-transformed infected vs. naïve") +
      xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
      ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)+
      coord_fixed(ratio = sd_ratio) +
      scale_shape_manual(values = c(17,15)) + 
      scale_color_manual(values = c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#ffff99", "#b15928"))
dev.off()


# Heatmap clusterring

annotation_for_heatmap <- data.frame(infection = pData(x.lumi.sub.TNQ)$"infection", day = pData(x.lumi.sub.TNQ)$"day")

row.names(annotation_for_heatmap) <- row.names(pData(x.lumi.sub.TNQ))

dists <- as.matrix(dist(t(exp_raw), method = "euclidean"))

rownames(dists) <- row.names(pData(x.lumi.sub.TNQ))
hmcol <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd"))(255))
colnames(dists) <- NULL
diag(dists) <- NA

ann_colors <- list(infection = c(naïve = "cadetblue2", infected = "blue4"),
                   day = c(D0 = "#1f78b4", D10 = "#33a02c", D12 = "#e31a1c", D2 = "#ff7f00", D4 = "#6a3d9a", D6 = "#ffff99", D8 = "#b15928"))
pdf(file = "fig/Heatmap_for_log2_spleen_sample.pdf")
pheatmap(dists, col = (hmcol),
         cellwidth = 10,
         cellheight = 10,
         labels_row = paste(x.lumi.GEO.AS.spleen$infection, x.lumi.GEO.AS.spleen$day),
         # annotation_row = annotation_for_heatmap,
         # annotation_colors = ann_colors,
         legend = TRUE, 
         treeheight_row = 0,
         # legend_breaks = c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE)), 
         # color = colorRampPalette(colors = c("blue","white","red")),
         # legend_labels = (c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE))),
         main = "Heatmap for vst-transformed spleen sample")
dev.off()





```









```{r}

# Data from CB Spleen

detDat <- detection(x.lumi.GEO.CB.spleen)
ggplot(data=melt(detDat), aes(x = Var2, y = value)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Detection Pval") +
  xlab("Sample") +
  ylab("Detection Pval")

True_Detection <- as.data.frame(colSums(detection(x.lumi.GEO.CB.spleen) <= 0.01 ))
# pdf(file = "fig/True_Detection_of_CB_spleen.pdf")
ggplot(data = True_Detection, aes(x = rownames(True_Detection),
                                  y = True_Detection[,1], group = 1,
                                  label = True_Detection[,1])) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  geom_point() +
  geom_line(linetype = 2) +
  geom_text(vjust = -1, nudge_y = 0.5) +
  ggtitle("True Detection") +
  xlab("Samples") +
  ylab("Detected Probes") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  scale_x_discrete(labels = paste(x.lumi.GEO.CB.spleen$infection,
                                  x.lumi.GEO.CB.spleen$day) )
# dev.off()

###Generate QC plots

plot(x.lumi.GEO.AS.spleen, what = 'density')
plotCDF(x.lumi.GEO.AS.spleen, reverse = T)
# plot(x.lumi.GEO.AS.spleen, what = 'pair')
# pairs(x.lumi.GEO.AS.spleen, smoothScatter = T)
MAplot(x.lumi.GEO.AS.spleen, smoothScatter = T)
plot(x.lumi.GEO.AS.spleen, what = 'boxplot')
plotSampleRelation(x.lumi.GEO.AS.spleen, method = 'mds')
plotSampleRelation(x.lumi.GEO.AS.spleen, method = 'cluster')

```

```{r}

##Do default VST variance stabilizing transform

x.lumi.sub.T <- lumiT(x.lumi.GEO.CB.spleen, method = 'log2')

##Plot VST transformation

# trans <- plotVST(x.lumi.sub.T)
# matplot(log2(trans$untransformed), trans$transformed)

##Do quantile between microarray normaliazation
x.lumi.sub.TN <- lumiN(x.lumi.sub.T)

##Do quality control estimation after normalization
x.lumi.sub.TNQ <- lumiQ(x.lumi.sub.TN)

###Generate QC plots after normalisation

plot(x.lumi.sub.TNQ, what = 'density')
# Density plot using ggplot2
expr <- exprs(x.lumi.sub.TNQ)
if (max(expr, na.rm = TRUE) > 50) {
  if (min(expr, na.rm = TRUE) < 0) {
    rMin <- rowMin(expr)
    expr <- expr[rMin > 0, , drop = FALSE]
    }
  expr <- log2(expr)
}
expr.x.lumi.sub.TNQ <- expr %>% t %>% data.frame(Sample.Name = sampleNames(x.lumi.sub.TNQ),
                      infection = x.lumi.sub.TNQ$infection)
expr.melt <- melt(expr.x.lumi.sub.TNQ, id = c("Sample.Name", "infection"))
colnames(expr.melt)[3:4] <- c("Symbol", "Intensity")

# pdf(file = "fig/Histogram_of_spleen_Expression_density.pdf")
ggplot(expr.melt, aes(Intensity, group = Sample.Name, col = infection, linetype = infection)) +
  stat_density(position="identity",geom = "line") +
  scale_linetype_manual(values=c(1, 2)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Histogram of Expression") + ylab("Density") + xlab("Expression")
# dev.off()


plotCDF(x.lumi.sub.TNQ, reverse = T)
# plot(x.lumi.sub.TNQ, what = 'boxplot')

randIDs <- sample(featureNames(x.lumi.sub.TNQ), 3000)
# pdf(file = "fig/Boxplot_of_CB_spleen_sample_microarray_intensity.pdf")
ggplot( melt(exprs(x.lumi.sub.TNQ[randIDs,])) , aes(x = Var2, y = value) ) +
  stat_boxplot(geom = "errorbar", width = 0.3) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
  geom_boxplot(outlier.shape = 1, outlier.size = 0.1, alpha = 1/3) +
  # geom_jitter(shape=".", position=position_jitter(0.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1) ) +
  scale_x_discrete(labels = paste(x.lumi.GEO.CB.spleen$infection,
                                  x.lumi.GEO.CB.spleen$day) ) +
  ggtitle("Boxplot of spleen sample microarray intensity") +
  xlab("Sample") +
  ylab("log2 transformed intensity (Rnd sampled 3000)")
# dev.off()


# plot(x.lumi.sub.TNQ, what = 'pair')
# pairs(x.lumi.sub.TNQ, smoothScatter = T)
MAplot(x.lumi.sub.TNQ, smoothScatter = T)
plotSampleRelation(x.lumi.sub.TNQ, method = 'mds')

# pdf(file = "fig/Sample_cluster_of_CB_spleen.pdf")
plotSampleRelation(x.lumi.sub.TNQ, method = 'cluster',
                   labels = paste(x.lumi.sub.TNQ$infection, x.lumi.sub.TNQ$day))
# dev.off()

# The PCA plot of the vst-transformed raw expression data
exp_raw <- exprs(x.lumi.sub.TNQ)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                    infection = pData(x.lumi.GEO.CB.spleen)$"infection",
                    day = pData(x.lumi.GEO.CB.spleen)$"day")

# pdf(file = "fig/PCA_plot_of_log2_INFvNAIVE_CB_spleen.pdf")
ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(shape = infection, colour = day), size = 3) +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      ggtitle("PCA plot of the log2-transformed infected vs. naïve") +
      xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
      ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)+
      coord_fixed(ratio = sd_ratio) +
      scale_shape_manual(values = c(17,15)) + 
      scale_color_manual(values = c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#ffff99", "#b15928", "#999999"))
# dev.off()


# Heatmap clusterring

annotation_for_heatmap <- data.frame(infection = pData(x.lumi.sub.TNQ)$"infection", day = pData(x.lumi.sub.TNQ)$"day")

row.names(annotation_for_heatmap) <- row.names(pData(x.lumi.sub.TNQ))

dists <- as.matrix(dist(t(exp_raw), method = "euclidean"))

rownames(dists) <- row.names(pData(x.lumi.sub.TNQ))
hmcol <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd"))(255))
colnames(dists) <- NULL
diag(dists) <- NA

ann_colors <- list(infection = c(naïve = "cadetblue2", infected = "blue4"),
                   day = c(D0 = "#1f78b4", D10 = "#33a02c", D12 = "#e31a1c", D2 = "#ff7f00", D4 = "#6a3d9a", D6 = "#ffff99", D8 = "#b15928", D9 = "#999999"))
# pdf(file = "fig/Heatmap_for_log2_CB_spleen_sample.pdf")
pheatmap(dists, col = (hmcol),
         cellwidth = 10,
         cellheight = 10,
         labels_row = paste(x.lumi.GEO.CB.spleen$infection, x.lumi.GEO.CB.spleen$day),
         # annotation_row = annotation_for_heatmap,
         # annotation_colors = ann_colors,
         legend = TRUE, 
         treeheight_row = 0,
         # legend_breaks = c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE)), 
         # color = colorRampPalette(colors = c("blue","white","red")),
         # legend_labels = (c(min(dists, na.rm = TRUE), 
         #                 max(dists, na.rm = TRUE))),
         main = "Heatmap for vst-transformed spleen sample")
# dev.off()





```





